package pojos;
// Generated May 25, 2018 3:38:54 PM by Hibernate Tools 4.3.1



/**
 * Exercise generated by hbm2java
 */
public class Exercise  implements java.io.Serializable {


     private Integer id;
     private String age;
     private String language;
     private int number;
     private int year;
     private String answer;
     private String url;

    public Exercise() {
    }

	
    public Exercise(String age, String language, int number, int year) {
        this.age = age;
        this.language = language;
        this.number = number;
        this.year = year;
    }
    public Exercise(String age, String language, int number, int year, String answer, String url) {
       this.age = age;
       this.language = language;
       this.number = number;
       this.year = year;
       this.answer = answer;
       this.url = url;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


