/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import dao.RoleDAO;
import main.MainWindow;
import common.RootWindow;
import object.Role;

/**
 *
 * @author Admin
 */
public class NewRolePanel extends RootWindow {

    MainWindow mainFrame;
    RoleDAO roleDAO;
    Role role = new Role();

    public NewRolePanel(MainWindow mainwindow) {
        initComponents();
        this.mainFrame = mainwindow;
        this.roleDAO = mainFrame.getDbManager().getRoleDAO();
        afterInitComponents();
    }

    private void afterInitComponents() {
        setSize(400, 400);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRoleName = new javax.swing.JLabel();
        txtlRoleName = new javax.swing.JTextField();
        butRoleCancel = new javax.swing.JButton();
        butRoleOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelRoleName.setText("Role name:");

        butRoleCancel.setText("Cancel");
        butRoleCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRoleCancelActionPerformed(evt);
            }
        });

        butRoleOK.setText("OK");
        butRoleOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRoleOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRoleName)
                    .addComponent(butRoleCancel))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtlRoleName)
                    .addComponent(butRoleOK, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRoleName)
                    .addComponent(txtlRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butRoleCancel)
                    .addComponent(butRoleOK))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butRoleOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRoleOKActionPerformed
        role.setName(txtlRoleName.getText());
        roleDAO.doRoleInsert(role);
    }//GEN-LAST:event_butRoleOKActionPerformed

    private void butRoleCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRoleCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_butRoleCancelActionPerformed

    @Override
    public void refresh() {
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butRoleCancel;
    private javax.swing.JButton butRoleOK;
    private javax.swing.JLabel labelRoleName;
    private javax.swing.JTextField txtlRoleName;
    // End of variables declaration//GEN-END:variables
}
