/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import dao.RoleDAO;
import dao.UserDAO;
import dao.UserrolesDAO;
import java.util.ArrayList;
import main.MainWindow;
import common.RootWindow;
import object.Role;
import object.User;
import object.Userroles;

/**
 *
 * @author Admin
 */
public class NewUserPanel extends RootWindow {

    MainWindow mainFrame;
    UserDAO userDAO;
    RoleDAO roleDAO;
    UserrolesDAO userrolesDAO;
    User user = new User();
    Role role = new Role();

    public NewUserPanel() {
        initComponents();
    }

    public NewUserPanel(MainWindow mainwindow) {
        initComponents();
        this.mainFrame = mainwindow;
        this.userDAO = mainFrame.getDbManager().getUserDao();
        this.roleDAO = mainFrame.getDbManager().getRoleDAO();
        this.userrolesDAO = mainFrame.getDbManager().getUserrolesDAO();

        afterInitComponents();
    }

    private void afterInitComponents() {
        setSize(400, 400);
        setRoles();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bUserOK = new javax.swing.JButton();
        bUserCancel = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        labUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbUserRoles = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        passwdUser = new javax.swing.JPasswordField();
        labName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();

        bUserOK.setText("OK");
        bUserOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUserOKActionPerformed(evt);
            }
        });

        bUserCancel.setText("Cancel");
        bUserCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUserCancelActionPerformed(evt);
            }
        });

        labUsername.setText("User name:");

        jLabel2.setText("Password: ");

        jLabel3.setText("Role:");

        passwdUser.setText("123456");

        labName.setText("Name: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(bUserCancel)
                    .addComponent(jLabel2)
                    .addComponent(labName)
                    .addComponent(labUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bUserOK)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbUserRoles, 0, 144, Short.MAX_VALUE)
                                .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(passwdUser)))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUsername)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbUserRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bUserOK)
                    .addComponent(bUserCancel))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bUserOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUserOKActionPerformed
        addUser();
        addUserrole();
    }//GEN-LAST:event_bUserOKActionPerformed

    private void bUserCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUserCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bUserCancelActionPerformed

    public void addUser() {
        user.setUsername(txtUserName.getText());
        user.setPassword(new String(passwdUser.getPassword()));
        user.setFullname(txtName.getText());
        userDAO.doUserInsert(user);
    }

    public void addUserrole() {
        Userroles userroles = new Userroles();
        String rolename = (String) this.cbUserRoles.getSelectedItem();
        role = roleDAO.getRole(rolename);
        User luser = userDAO.getUser(user.getUsername());
        userroles.setRole_id(role.getId());
        userroles.setUser_id(luser.getId());
        userrolesDAO.doUserRolesInsert(userroles);
    }

    public void setRoles() {
        ArrayList<Role> roles = new ArrayList<Role>();
        roles = roleDAO.getAllRoles();
        for (Role role : roles) {
            this.cbUserRoles.addItem(role.getName());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bUserCancel;
    private javax.swing.JButton bUserOK;
    private javax.swing.JComboBox<String> cbUserRoles;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labUsername;
    private javax.swing.JPasswordField passwdUser;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
        repaint();
    }
}
