/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import dao.UserrolesDAO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import object.Role;
import object.RoleCellEditor;
import object.RoleCellRendered;
import object.User;
import object.UserTableModel;
import object.Userroles;

/**
 *
 * @author Admin
 */
public class UserRolePanel extends javax.swing.JPanel {

    private boolean DEBUG = false;
    ArrayList<User> users = new ArrayList<User>();
    ArrayList<Userroles> userroles = new ArrayList<Userroles>();
    ArrayList<Role> roles = new ArrayList<Role>();
    UserrolesDAO userrolesDAO;
    JComboBox box = new JComboBox();

    String sUsername;
    String sPassword;
    String sAuthirity;

    private JTable table = new JTable();
    private UserTableModel tableModel;

    public UserRolePanel(ArrayList<User> luserek, ArrayList<Role> roles, UserrolesDAO userrolesdao) {
        this.users = luserek;
        this.userrolesDAO = userrolesdao;
        this.roles = roles;
        initComponents();
        afterInit();
    }

    public void afterInit() {

        tableModel = new UserTableModel(users);
        table.setModel(tableModel);
        table.setDefaultRenderer(Role.class, new RoleCellRendered());
        table.setDefaultEditor(Role.class, new RoleCellEditor(roles));
        table.setRowHeight(25);

        JScrollPane scrollpane = new JScrollPane(table);
        scrollpane.setPreferredSize(new Dimension(400, 200));

        add(scrollpane, BorderLayout.CENTER);
        table.setFillsViewportHeight(true);
        table.setAutoCreateRowSorter(true);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // itt tudom beállítani,hogy hány sort töröljön ki
        table.setSize(600, 800);
        table.setSize(getPreferredSize());

        /*   table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (DEBUG) {
                    printDebugData(table);
                }
                JTable target = (JTable) e.getSource();
                MouseAdapterForUserPanel MyMause = new MouseAdapterForUserPanel(users);
                sUsername = MyMause.getUserName(e);
            }
        });*/
        //Create the scroll pane and add the table to it.
        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setSize(getPreferredSize());
        //Add the scroll pane to this panel.
        add(scrollPane);
        // setSize(600, 400);
        setVisible(true);
        revalidate();
        repaint();
        setVisible(true);
    }

    private void printDebugData(JTable table) {
        int numRows = table.getRowCount();
        int numCols = table.getColumnCount();
        javax.swing.table.TableModel model = table.getModel();

        System.out.println("Value of data: ");
        for (int i = 0; i < numRows; i++) {
            System.out.print("    row " + i + ":");
            for (int j = 0; j < numCols; j++) {
                System.out.print("  " + model.getValueAt(i, j));
            }
            System.out.println();
        }
        System.out.println("--------------------------");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
