/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import dao.ExerciseDAO;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import main.MainWindow;
import common.RootWindow;
import object.Exercise;
import object.ExercisesList;
import util.Utility;

/**
 *
 * @author Admin
 */
public class XmlToDBPanel extends RootWindow {

    MainWindow mainFrame;
    ExerciseDAO exerciseDAO;
    private String placeOfXml;
    ArrayList<Exercise> exercises = new ArrayList<>();
 
    public XmlToDBPanel() {
        initComponents();
    }

    public XmlToDBPanel(MainWindow mainwindow) {
        initComponents();
        this.mainFrame = mainwindow;
        afterInitComponents();
    }

    private void afterInitComponents() {
        placeOfXml = mainFrame.getSystemConfig().getProperty("placeOfXml");
        this.exerciseDAO = mainFrame.getDbManager().getExerciseDAO();
        setSize(400, 400);
        refresh();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSelFilesToDB = new javax.swing.JTextField();
        butXmltoDBOK = new javax.swing.JButton();
        buSavaXmlCancelToDB = new javax.swing.JButton();
        butSelFilesToDB = new java.awt.Button();
        labSelFilesToDB = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butXmltoDBOK.setText("Xml To DB");
        butXmltoDBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXmltoDBOKActionPerformed(evt);
            }
        });

        buSavaXmlCancelToDB.setText("Cancel");
        buSavaXmlCancelToDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSavaXmlCancelToDBActionPerformed(evt);
            }
        });

        butSelFilesToDB.setLabel(".....");
        butSelFilesToDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSelFilesToDBActionPerformed(evt);
            }
        });

        labSelFilesToDB.setText("Select files:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buSavaXmlCancelToDB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butXmltoDBOK, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labSelFilesToDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txtSelFilesToDB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(butSelFilesToDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labSelFilesToDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butSelFilesToDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSelFilesToDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butXmltoDBOK)
                    .addComponent(buSavaXmlCancelToDB))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butXmltoDBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXmltoDBOKActionPerformed
        System.out.println("itt vagyok");
        for (Exercise exercise : exercises) {
            exerciseDAO.doExerciseInsert(exercise);
        }
    }//GEN-LAST:event_butXmltoDBOKActionPerformed

    private void buSavaXmlCancelToDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSavaXmlCancelToDBActionPerformed
        setVisible(false);
    }//GEN-LAST:event_buSavaXmlCancelToDBActionPerformed

    private void butSelFilesToDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSelFilesToDBActionPerformed
        File selectedFile = Utility.getSelectedFile(placeOfXml);
        ExercisesList exercisesList = null;
        try {
            JAXBContext jaxbContext = JAXBContext.newInstance(ExercisesList.class);
            Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
            exercisesList = (ExercisesList) jaxbUnmarshaller.unmarshal(selectedFile);
        } catch (JAXBException ex) {
            Logger.getLogger(XmlToDBPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Exercise exercise : exercisesList.getExercises()) {
            System.out.println(exercise);
            exercises.add(exercise);
        }

    }//GEN-LAST:event_butSelFilesToDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XmlToDBPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XmlToDBPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XmlToDBPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XmlToDBPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XmlToDBPanel().setVisible(true);
            }
        });
    }

    @Override
    public void refresh() {
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buSavaXmlCancelToDB;
    private java.awt.Button butSelFilesToDB;
    private javax.swing.JButton butXmltoDBOK;
    private java.awt.Label labSelFilesToDB;
    private javax.swing.JTextField txtSelFilesToDB;
    // End of variables declaration//GEN-END:variables
}
